housepowerconsump <- read_delim("household_power_consumption.txt", delim = ";")
housepowerconsumpdate <- housepowerconsump[66637:69516,]
DateTime <- paste(housepowerconsumpdate$Date, housepowerconsumpdate$Time, sep="-")
strpDateTime <- strptime(DateTime, "%d/%m/%Y-%H:%M:%S")
housepowerconsumpdate <- cbind(housepowerconsumpdate, strpDateTime)
png("plot4.png", width=480, height=480)
par(mfrow =c(2,2))
with(housepowerconsumpdate, plot(strpDateTime, Global_active_power, pch=NA_integer_, type="l", ylab="Global Active Power", xlab=""))
with(housepowerconsumpdate, plot(strpDateTime, Voltage, pch=NA_integer_, type="l", ylab="Voltage", xlab="datetime"))
with(housepowerconsumpdate, plot(strpDateTime, Sub_metering_1, ylab="Energy sub metering", type="l", xlab=""))
        lines(x=(housepowerconsumpdate$strpDateTime),y=housepowerconsumpdate$Sub_metering_2,col="red")
        lines(x=(housepowerconsumpdate$strpDateTime),y=housepowerconsumpdate$Sub_metering_3,col="blue")
        legend("topright", lty=1, col = c("black", "blue", "red"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), bty="n")
with(housepowerconsumpdate, plot(strpDateTime, Global_reactive_power, pch=NA_integer_, type="l", ylab="Global_reactive_power", xlab="datetime"))
dev.off()